addr = '127.0.0.1:8090'
signup_enabled = true
title = 'Bmtdblog'
session_secret = 'Bmtdblog'
domain = 'http://localhost:8090'
file_server = 'smms'
notify_emails = ''
page_size = 10
public = 'static'
view = 'views/**/*.html'
dir = '.'

[database]
dsn = 'bmtdblog.db'

[elasticsearch]
enabled = false
host = 'localhost:9200'
index_name = 'bmtdblog_posts'
username = ''
password = ''

[seo]
description = 'Bmtdblog, just my toy'

[seo.author]
name = 'xiuivfbc'
email = '3138910969@qq.com'

[qiniu]
enabled = false
accesskey = ''
secretkey = ''
fileserver = ''
bucket = 'Bmtdblog'

[smms]
enabled = false
apiurl = 'https://sm.ms/api/v2/upload'
apikey = ''

[redis]
enabled = false
addr = ''
password = ''
db = 0
pool_size = 10

[github]
enabled = false
clientid = ''
clientsecret = ''
redirecturl = 'http://localhost:8090/oauth2callback'
authurl = 'https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s'
tokenurl = 'https://github.com/login/oauth/access_token'
scope = ''

[smtp]
enabled = false
username = ''
password = ''
host = 'smtp.qq.com:587'

[[navigators]]
title = 'Posts'
url = '/index'
target = ''

[[navigators]]
title = 'AboutMe'
url = '/page/1'
target = ''

[[navigators]]
title = 'RSS'
url = '/rss'
target = '_blank'

[[navigators]]
title = 'Subscribe'
url = '/subscribe'
target = ''

[backup]
enabled = false
backup_key = ''
