addr = '127.0.0.1:8090'
signup_enabled = true
title = 'bmtdblog'
session_secret = 'bmtdblog'
domain = 'http://localhost'
file_server = 'smms'
notify_emails = ''
page_size = 10
public = 'static'
view = 'views/**/*'

[database]
dsn = 'cp:cp123456@tcp(127.0.0.1:3306)/bmtdblog?charset=utf8mb4&parseTime=True&loc=Local'

[seo]
description = 'bmtdblog, just my toy'

[seo.author]
name = 'hvfwdemc'
email = '3138910969@qq.com'

[qiniu]
enabled = false
accesskey = ''
secretkey = ''
fileserver = ''
bucket = 'bmtdblog'

[smms]
enabled = false
apiurl = 'https://sm.ms/api/v2/upload'
apikey = ''

[github]
enabled = false
clientid = ''
clientsecret = ''
redirecturl = 'https://example.com/oauth2callback'
authurl = 'https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s'
tokenurl = 'https://github.com/login/oauth/access_token'
scope = ''

[smtp]
enabled = false
username = ''
password = ''
host = 'smtp.163.com:25'

[[navigators]]
title = 'Posts'
url = '/index'
target = ''

[[navigators]]
title = 'AboutMe'
url = '/page/6'
target = ''

[[navigators]]
title = 'RSS'
url = '/rss'
target = '_blank'

[[navigators]]
title = 'Subscribe'
url = '/subscribe'
target = ''

[backup]
enabled = false
backup_key = ''
